name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: g++ -std=c++17 VA_main.cpp VA_BloodDonation.cpp VA_VacationAccount.cpp -o va
